"""initial schema

Revision ID: 0717ad25160a
Revises: 
Create Date: 2026-04-11 18:15:53.696490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0717ad25160a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('source_path', sa.Text(), nullable=False),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.Column('total_turns', sa.Integer(), nullable=False),
    sa.Column('total_tokens_est', sa.Integer(), nullable=False),
    sa.Column('manifest', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('start_turn', sa.Integer(), nullable=False),
    sa.Column('end_turn', sa.Integer(), nullable=False),
    sa.Column('overlap_start_turn', sa.Integer(), nullable=True),
    sa.Column('token_estimate', sa.Integer(), nullable=False),
    sa.Column('hot_zone_count', sa.Integer(), nullable=False),
    sa.Column('contains_compact_boundary', sa.Boolean(), nullable=False),
    sa.Column('extraction_status', sa.String(length=20), nullable=False),
    sa.Column('extraction_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extraction_model', sa.String(length=100), nullable=True),
    sa.Column('extraction_cost_est', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chunks_session_index', 'chunks', ['session_id', 'chunk_index'], unique=False)
    op.create_table('narratives',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('parent_revision', sa.Integer(), nullable=True),
    sa.Column('content_md', sa.Text(), nullable=False),
    sa.Column('synthesis_model', sa.String(length=100), nullable=True),
    sa.Column('user_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('annotations_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_narratives_session_rev', 'narratives', ['session_id', 'revision'], unique=False)
    op.create_table('turns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('turn_index', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('tool_calls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_compact_boundary', sa.Boolean(), nullable=False),
    sa.Column('is_error', sa.Boolean(), nullable=False),
    sa.Column('token_estimate', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('raw_jsonl_line', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('message_uuid', sa.String(length=100), nullable=True),
    sa.Column('parent_uuid', sa.String(length=100), nullable=True),
    sa.Column('is_sidechain', sa.Boolean(), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('token_usage', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('has_thinking', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_turns_session_compact', 'turns', ['session_id', 'is_compact_boundary'], unique=False)
    op.create_index('ix_turns_session_error', 'turns', ['session_id', 'is_error'], unique=False)
    op.create_index('ix_turns_session_turn', 'turns', ['session_id', 'turn_index'], unique=False)
    op.create_table('annotations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('narrative_id', sa.UUID(), nullable=False),
    sa.Column('section_path', sa.String(length=500), nullable=False),
    sa.Column('annotation_type', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_chunk_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['narrative_id'], ['narratives.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('annotations')
    op.drop_index('ix_turns_session_turn', table_name='turns')
    op.drop_index('ix_turns_session_error', table_name='turns')
    op.drop_index('ix_turns_session_compact', table_name='turns')
    op.drop_table('turns')
    op.drop_index('ix_narratives_session_rev', table_name='narratives')
    op.drop_table('narratives')
    op.drop_index('ix_chunks_session_index', table_name='chunks')
    op.drop_table('chunks')
    op.drop_table('sessions')
    # ### end Alembic commands ###
