"""add subagent and artifact columns

Revision ID: 0c2dab85c64a
Revises: 0717ad25160a
Create Date: 2026-04-11 20:24:13.343695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0c2dab85c64a'
down_revision: Union[str, Sequence[str], None] = '0717ad25160a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('artifact_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('sessions', sa.Column('parent_session_id', sa.UUID(), nullable=True))
    op.add_column('sessions', sa.Column('session_type', sa.String(length=20), server_default='main', nullable=False))
    op.add_column('sessions', sa.Column('agent_type', sa.String(length=50), nullable=True))
    op.add_column('sessions', sa.Column('agent_description', sa.String(length=1000), nullable=True))
    op.create_foreign_key(None, 'sessions', 'sessions', ['parent_session_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_column('sessions', 'agent_description')
    op.drop_column('sessions', 'agent_type')
    op.drop_column('sessions', 'session_type')
    op.drop_column('sessions', 'parent_session_id')
    op.drop_column('chunks', 'artifact_result')
    # ### end Alembic commands ###
